<a href="https://colab.research.google.com/github/RahulYadav71/Data-Science-and-Ai-python-Programming-Module--01/blob/Pandas/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Pandas**

Pandas is an open-source Python library used for data manipulation and data analysis.

# Why do we used Pandas?

Pandas is used to read, clean,organize,filter,analyze, and manipulate structured data efficiently.

# **Features of Pandas**

# 1. Data Manipulation

Used to modify,organize and transform data easily.

# 2. Data Analysis

Used to analyze data and extract meaningful insights.

# 3. Fast Processing

Handles large datasets efficiently with optimized performance.

#4. Missing Value Handling

Allows easy detection and handling of missing values.

#5. File Handling

Can read and write CSV, Excel, JSON,SQL,and many other file formats.

#6. Data Filtering

Used to select specific rows and columns based on conditions.

#7. Data Cleaning

Removes duplicate,  incorrect,or unnecessary data.

#8. Statistical Analysis

Provides built-in-functions for statistical calculations

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# Main Data Structure in Pandas

1. series A series is a one-dimensional labeled array that stores a single column of data.

2. DataFrame A Dataframe is a two-dimensional labeled table consisting of rows and columns.

# **1. Creating series**

In [ ]:
import pandas as pd

marks = pd.Series([85,90,95,78,98])

print(marks)

0    85
1    90
2    95
3    78
4    98
dtype: int64

# 2.**String Series**

In [ ]:
import pandas as pd

names = pd.Series(["Aman", "khushi", "Pradeep","Gaurangi"])

print(names)

0        Aman
1      khushi
2     Pradeep
3    Gaurangi
dtype: object

# **3. Custom Index**

In [ ]:
import pandas as pd

marks = pd.Series(
    [85,90,78],
    index=["Maths", "Science", "English"]
)

print(marks)

Maths      85
Science    90
English    78
dtype: int64

Create a Series from a Dictionary

In [ ]:
import pandas as pd

student = pd.Series({
    "Name":"Rahul",
    "Age":20,
    "City":"Lucknow"
})

print(student)

Name      Rahul
Age          20
City    Lucknow
dtype: object

Access Values in a Series.

In [ ]:
import pandas as pd

marks = pd.Series([85,90,78,92])

print(marks[0])
print(marks[2])

85
78

Access Values Using Custom Index.

In [ ]:
import pandas as pd

marks = pd.Series(
    [85,90,78,92],
    index=["Maths", "Science", "English", "Social"]
)

print(marks["Science"])

90

Print Series Information.

In [ ]:
import pandas as pd

marks = pd.Series([85,90,78])

print(type(marks))
print(marks.dtype)
print(marks.size)

<class 'pandas.core.series.Series'>
int64
3

# **Creating DataFrame**

***DataFrame is a 2D labeled table consisting of rows and columns A.***

***DataFrame is used to store,organize,manipulate, and analyze tabular data efficiently.***

# Syntax

import pandas as pd

df = pd.DataFrame(data)

In [ ]:
import pandas as pd

student = {
    "Name" : ["Aman", "Ravi", "Khushi", "Gaurangi"],
    "Age" : [20,21,25,22],
    "City" : ["Lucknow", "Delhi", "Mumbai", "Pune"]
}
df = pd.DataFrame(student)

print(df)

       Name  Age     City
0      Aman   20  Lucknow
1      Ravi   21    Delhi
2    Khushi   25   Mumbai
3  Gaurangi   22     Pune

Create DataFrame with custom Index.

In [ ]:
import pandas as pd

student = {
    "Name" : ["Rahul", "Pradeep", "Rohan"],
    "Marks" : [85, 90, 78]
}

df = pd.DataFrame(student, index=["S1", "S2", "S3"])

print(df)

       Name  Marks
S1    Rahul     85
S2  Pradeep     90
S3    Rohan     78

Create a DataFrame from a List of Lists.

In [ ]:
import pandas as pd
data = [
    ["Rahul", 20, "Lucknow"],
    ["Pradeep", 21, "Delhi"],
    ["Rohan", 22, "Mumbai"]
]

df = pd.DataFrame(data, columns=["Name", "Age", "City"])

print(df)

      Name  Age     City
0    Rahul   20  Lucknow
1  Pradeep   21    Delhi
2    Rohan   22   Mumbai

Create a DataFrame from a List of Dictionaries.

In [ ]:
import pandas as pd

data = [
    {"Name": "Rahul", "Age": 20,},
    {"Name": "Pradeep", "Age": 21,},
    {"Name": "Rohan", "Age": 22,}
]

df = pd.DataFrame(data)

print(df)

      Name  Age
0    Rahul   20
1  Pradeep   21
2    Rohan   22

Create an Empty DataFrame.

In [ ]:
import pandas as pd

df_empty = pd.DataFrame()

print(df_empty)

Empty DataFrame
Columns: []
Index: []

# **Module 2 - Reading and Writing Data**

# 1.read_csv()

***read_csv() is used to read data from a CSV file into a Pandas DataFrame.***

In [ ]:
import pandas as pd

df = pd.read_csv("/content/student.csv")

print(df)

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0    ...      4        3      4     1     1      3        6   5   6   6
1    ...      5        3      3     1     1      3        4   5   5   6
2    ...      4        3      2     2     3      3       10   7   8  10
3    ...      3        2      2     1     1      5        2  15  14  15
4    ...      4        3      2     1     2      5        4   6  10  10
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[395 rows x 33 columns]

Display First Five Rows.

In [ ]:
import pandas as pd

df = pd.read_csv("/content/student.csv")

print(df.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...
3     GP   F   15       U     GT3       T     4     2   health  services  ...
4     GP   F   16       U     GT3       T     3     3    other     other  ...

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0      4        3      4     1     1      3        6   5   6   6
1      5        3      3     1     1      3        4   5   5   6
2      4        3      2     2     3      3       10   7   8  10
3      3        2      2     1     1      5        2  15  14  15
4      4        3      2     1     2      5        4   6  10  10

[5 rows x 33 columns]

Display last five rows.

In [ ]:
import pandas as pd

df = pd.read_csv("/content/student.csv")

print(df.tail())

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[5 rows x 33 columns]

Store Using Another Variable Name.

In [ ]:
import pandas as pd

students = pd.read_csv("/content/student.csv")

print(students)

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0    ...      4        3      4     1     1      3        6   5   6   6
1    ...      5        3      3     1     1      3        4   5   5   6
2    ...      4        3      2     2     3      3       10   7   8  10
3    ...      3        2      2     1     1      5        2  15  14  15
4    ...      4        3      2     1     2      5        4   6  10  10
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[395 rows x 33 columns]

Read First 10 Rows.

In [ ]:
import pandas as pd

students = pd.read_csv("/content/student.csv")

print(students.head(10))

  school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0     GP   F   18       U     GT3       A     4     4   at_home   teacher
1     GP   F   17       U     GT3       T     1     1   at_home     other
2     GP   F   15       U     LE3       T     1     1   at_home     other
3     GP   F   15       U     GT3       T     4     2    health  services
4     GP   F   16       U     GT3       T     3     3     other     other
5     GP   M   16       U     LE3       T     4     3  services     other
6     GP   M   16       U     LE3       T     2     2     other     other
7     GP   F   17       U     GT3       A     4     4     other   teacher
8     GP   M   15       U     LE3       A     3     2  services     other
9     GP   M   15       U     GT3       T     3     4     other     other

   ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0  ...      4        3      4     1     1      3        6   5   6   6
1  ...      5        3      3     1     1      3        4   5   5   6
2  ...      4        3      2     2     3      3       10   7   8  10
3  ...      3        2      2     1     1      5        2  15  14  15
4  ...      4        3      2     1     2      5        4   6  10  10
5  ...      5        4      2     1     2      5       10  15  15  15
6  ...      4        4      4     1     1      3        0  12  12  11
7  ...      4        1      4     1     1      1        6   6   5   6
8  ...      4        2      2     1     1      1        0  16  18  19
9  ...      5        5      1     1     1      5        0  14  15  15

[10 rows x 33 columns]

***Read Selected Columns.***

In [ ]:
import pandas as pd

df = pd.read_csv(
    "/content/student.csv",
    usecols=[
        "sex",
        "G1",
        "G2"
    ]
)

print(df)

    sex  G1  G2
0     F   5   6
1     F   5   5
2     F   7   8
3     F  15  14
4     F   6  10
..   ..  ..  ..
390   M   9   9
391   M  14  16
392   M  10   8
393   M  11  12
394   M   8   9

[395 rows x 3 columns]

# 2. read_excel()

***read_excel() is used to read data from an Excel(.xlsx) file and load it into a Pandas DataFrame.***

# **Prerequisite**

***To read Excel files, install the openpyxl library.***

***pip install openpyxl***

In [ ]:
import pandas as pd

df = pd.read_csv("/content/student.csv")

df.to_excel("student.xlsx", index=False)

print("CSV successfullly converted to Excel!")

CSV successfullly converted to Excel!

***Read Excel file.***

In [ ]:
import pandas as pd

df = pd.read_excel("/content/student.xlsx")

print(df)

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0    ...      4        3      4     1     1      3        6   5   6   6
1    ...      5        3      3     1     1      3        4   5   5   6
2    ...      4        3      2     2     3      3       10   7   8  10
3    ...      3        2      2     1     1      5        2  15  14  15
4    ...      4        3      2     1     2      5        4   6  10  10
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[395 rows x 33 columns]

***Display First Five Rows.***

In [ ]:
import pandas as pd

df = pd.read_excel("/content/student.xlsx")

print(df.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...
3     GP   F   15       U     GT3       T     4     2   health  services  ...
4     GP   F   16       U     GT3       T     3     3    other     other  ...

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0      4        3      4     1     1      3        6   5   6   6
1      5        3      3     1     1      3        4   5   5   6
2      4        3      2     2     3      3       10   7   8  10
3      3        2      2     1     1      5        2  15  14  15
4      4        3      2     1     2      5        4   6  10  10

[5 rows x 33 columns]

***Display Last Five Rows.***

In [ ]:
import pandas as pd

df = pd.read_excel("/content/student.xlsx")

print(df.tail())

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[5 rows x 33 columns]

***Read First 10 Rows.***

In [ ]:
import pandas as pd

df = pd.read_excel("/content/student.xlsx")

print(df.head(10))

  school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0     GP   F   18       U     GT3       A     4     4   at_home   teacher
1     GP   F   17       U     GT3       T     1     1   at_home     other
2     GP   F   15       U     LE3       T     1     1   at_home     other
3     GP   F   15       U     GT3       T     4     2    health  services
4     GP   F   16       U     GT3       T     3     3     other     other
5     GP   M   16       U     LE3       T     4     3  services     other
6     GP   M   16       U     LE3       T     2     2     other     other
7     GP   F   17       U     GT3       A     4     4     other   teacher
8     GP   M   15       U     LE3       A     3     2  services     other
9     GP   M   15       U     GT3       T     3     4     other     other

   ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0  ...      4        3      4     1     1      3        6   5   6   6
1  ...      5        3      3     1     1      3        4   5   5   6
2  ...      4        3      2     2     3      3       10   7   8  10
3  ...      3        2      2     1     1      5        2  15  14  15
4  ...      4        3      2     1     2      5        4   6  10  10
5  ...      5        4      2     1     2      5       10  15  15  15
6  ...      4        4      4     1     1      3        0  12  12  11
7  ...      4        1      4     1     1      1        6   6   5   6
8  ...      4        2      2     1     1      1        0  16  18  19
9  ...      5        5      1     1     1      5        0  14  15  15

[10 rows x 33 columns]

***Read selected columns.***

In [ ]:
import pandas as pd

df = pd.read_excel(
    "/content/Student.xlsx",
    usecols=[
        "sex",
        "G1",
        "G2"
    ]
)

print(df)

    sex  G1  G2
0     F   5   6
1     F   5   5
2     F   7   8
3     F  15  14
4     F   6  10
..   ..  ..  ..
390   M   9   9
391   M  14  16
392   M  10   8
393   M  11  12
394   M   8   9

[395 rows x 3 columns]

# **Read json()**

***JSON (JavaScript Object Notation) is a lightweight data-interchange format.***

***It stores data as a key-value pairs.***

In [ ]:
import pandas as pd

#Read CSV file
df = pd.read_csv("student.csv")

#Convert CSV to JSON
df.to_json("student.json", orient="records", indent=4)

print("CSV converted to JSON!")

CSV converted to JSON!

In [ ]:
import pandas as pd

df = pd.read_json("/content/student.json")

print(df)

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0    ...      4        3      4     1     1      3        6   5   6   6
1    ...      5        3      3     1     1      3        4   5   5   6
2    ...      4        3      2     2     3      3       10   7   8  10
3    ...      3        2      2     1     1      5        2  15  14  15
4    ...      4        3      2     1     2      5        4   6  10  10
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[395 rows x 33 columns]

In [ ]:
import pandas as pd

df = pd.read_json("/content/student.json")

print(df.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...
3     GP   F   15       U     GT3       T     4     2   health  services  ...
4     GP   F   16       U     GT3       T     3     3    other     other  ...

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0      4        3      4     1     1      3        6   5   6   6
1      5        3      3     1     1      3        4   5   5   6
2      4        3      2     2     3      3       10   7   8  10
3      3        2      2     1     1      5        2  15  14  15
4      4        3      2     1     2      5        4   6  10  10

[5 rows x 33 columns]

In [ ]:
import pandas as pd

df = pd.read_json("/content/student.json")

print(df.tail())

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[5 rows x 33 columns]

# ** Sample()**

***The sample() function is used to select random rows from a DataFrame.***

***instead of displaying the first or last rows, it returns random records.***

# It is widely used in:
*1. Machine Learning*

*2. Data Analysis*

*3. Data Visualization*

*4. Random Testing*

*5. Survey Analysis*

*6. Exploratory Data Analysis (EDA)*

***Display one Random Student.***

In [ ]:
import pandas as pd

df = pd.read_csv("/content/student.csv")

print(df.sample())

   school sex  age address famsize Pstatus  Medu  Fedu   Mjob   Fjob  ...  \
33     GP   M   15       U     LE3       T     3     3  other  other  ...

   famrel freetime  goout  Dalc  Walc health absences G1  G2  G3
33      5        3      2     1     1      2        0  8  10  12

[1 rows x 33 columns]

***Display 5 random student***

In [ ]:
import pandas as pd

df = pd.read_csv("/content/student.csv")

print(df.sample(5))

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
134     GP   M   15       R     GT3       T     3     4   at_home   teacher
131     GP   F   15       U     GT3       T     1     1   at_home     other
38      GP   F   15       R     GT3       T     3     4  services    health
227     GP   M   17       U     LE3       T     2     3  services  services
87      GP   F   15       U     GT3       T     4     2     other     other

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
134  ...      5        3      3     1     1      5        0   9   0   0
131  ...      4        3      3     1     2      4        0   8   0   0
38   ...      4        3      2     1     1      5        2  12  12  11
227  ...      5        3      3     1     3      3        2  12  11  12
87   ...      5        3      3     1     3      1        4  13  14  14

[5 rows x 33 columns]

***Select 30% of Dataset***

In [ ]:
import pandas as pd

df = pd.read_csv("/content/student.csv")

print(df.sample(frac=0.3))

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
291     GP   F   17       U     GT3       T     4     3    health  services
173     GP   F   16       U     GT3       T     1     3   at_home  services
167     GP   F   16       U     GT3       T     4     2    health  services
272     GP   F   18       U     LE3       T     1     1     other     other
101     GP   M   16       U     GT3       T     4     4  services   teacher
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
213     GP   M   18       U     GT3       T     2     2  services     other
206     GP   F   16       U     GT3       A     3     1  services     other
200     GP   F   16       U     GT3       T     4     3    health     other
241     GP   M   17       R     LE3       A     4     4   teacher     other
379     MS   F   17       R     GT3       T     3     1   at_home     other

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
291  ...      4        2      2     1     2      3        0  15  15  15
173  ...      4        3      5     1     1      3        0   8   7   0
167  ...      4        2      3     1     1      3        0  14  15  16
272  ...      4        4      3     1     1      3        2  11  11  11
101  ...      4        4      3     1     1      4        0  16  17  17
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
213  ...      4        4      4     2     4      5       15   6   7   8
206  ...      2        3      3     2     2      4        5   7   7   7
200  ...      4        3      5     1     5      2        2  16  16  16
241  ...      3        3      3     2     3      4        2  10  11  12
379  ...      4        5      4     2     3      1       17  10  10  10

[118 rows x 33 columns]

***Random students from Excel File.***

In [ ]:
import pandas as pd

df = pd.read_excel("/content/student.xlsx")

print(df.sample(3))

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
129     GP   M   16       R     GT3       T     4     4   teacher   teacher
185     GP   M   17       U     GT3       T     3     3  services  services
139     GP   F   15       U     GT3       T     4     4   teacher   teacher

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
129  ...      3        5      5     2     5      4        8  18  18  18
185  ...      4        3      4     2     3      4       12  12  12  11
139  ...      4        3      2     1     1      5        0  16  16  15

[3 rows x 33 columns]

***Random students from JSON file.***

In [ ]:
import pandas as pd

df = pd.read_json("/content/student.json")

print(df.sample(2))

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob   Fjob  ...  \
260     GP   F   18       U     GT3       T     4     3  services  other  ...
351     MS   M   17       U     GT3       T     3     3    health  other  ...

    famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
260      3        1      2     1     3      2       21  17  18  18
351      4        5      4     2     3      3        2  13  13  13

[2 rows x 33 columns]

# **Module 3- DataFrame Information**

In [ ]:
import pandas as pd

df = pd.read_csv("/content/student.csv")

print(df.info()) #display a complete summary of the dataframe
print(df.shape) #returns the number of rows and columns
print(df.columns) #show all columns
print(df.index) #displays rows laber (index).
print(df.dtypes) #shows the data type of each column
print(df.size) #returns the total numbers of elements
print(df.ndim) #returns the number of dimensions
print(df.memory_usage) #displays memory used by each column.
print(df.describe()) #provides statistical summary of numberic columns.
print(df.describe(include='all')) #shows statics for all columns (numeric nd categorical)
print(df.count) #count non-mising values in each column.
print(df.isnull().sum()) #counts mising values
print(df.nunique()) #shows the number of unique values in each column.
print(df.value_counts()) #count unique rows.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB
None
(395, 33)
Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')
RangeIndex(start=0, stop=395, step=1)
school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object
13035
2
<bound method DataFrame.memory_usage of     school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0    ...      4        3      4     1     1      3        6   5   6   6
1    ...      5        3      3     1     1      3        4   5   5   6
2    ...      4        3      2     2     3      3       10   7   8  10
3    ...      3        2      2     1     1      5        2  15  14  15
4    ...      4        3      2     1     2      5        4   6  10  10
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[395 rows x 33 columns]>
              age        Medu        Fedu  traveltime   studytime    failures  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000
mean    16.696203    2.749367    2.521519    1.448101    2.035443    0.334177
std      1.276043    1.094735    1.088201    0.697505    0.839240    0.743651
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000
25%     16.000000    2.000000    2.000000    1.000000    1.000000    0.000000
50%     17.000000    3.000000    2.000000    1.000000    2.000000    0.000000
75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000
max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000

           famrel    freetime       goout        Dalc        Walc      health  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000
mean     3.944304    3.235443    3.108861    1.481013    2.291139    3.554430
std      0.896659    0.998862    1.113278    0.890741    1.287897    1.390303
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000
25%      4.000000    3.000000    2.000000    1.000000    1.000000    3.000000
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000

         absences          G1          G2          G3
count  395.000000  395.000000  395.000000  395.000000
mean     5.708861   10.908861   10.713924   10.415190
std      8.003096    3.319195    3.761505    4.581443
min      0.000000    3.000000    0.000000    0.000000
25%      0.000000    8.000000    9.000000    8.000000
50%      4.000000   11.000000   11.000000   11.000000
75%      8.000000   13.000000   13.000000   14.000000
max     75.000000   19.000000   19.000000   20.000000
       school  sex         age address famsize Pstatus        Medu  \
count     395  395  395.000000     395     395     395  395.000000
unique      2    2         NaN       2       2       2         NaN
top        GP    F         NaN       U     GT3       T         NaN
freq      349  208         NaN     307     281     354         NaN
mean      NaN  NaN   16.696203     NaN     NaN     NaN    2.749367
std       NaN  NaN    1.276043     NaN     NaN     NaN    1.094735
min       NaN  NaN   15.000000     NaN     NaN     NaN    0.000000
25%       NaN  NaN   16.000000     NaN     NaN     NaN    2.000000
50%       NaN  NaN   17.000000     NaN     NaN     NaN    3.000000
75%       NaN  NaN   18.000000     NaN     NaN     NaN    4.000000
max       NaN  NaN   22.000000     NaN     NaN     NaN    4.000000

              Fedu   Mjob   Fjob  ...      famrel    freetime       goout  \
count   395.000000    395    395  ...  395.000000  395.000000  395.000000
unique         NaN      5      5  ...         NaN         NaN         NaN
top            NaN  other  other  ...         NaN         NaN         NaN
freq           NaN    141    217  ...         NaN         NaN         NaN
mean      2.521519    NaN    NaN  ...    3.944304    3.235443    3.108861
std       1.088201    NaN    NaN  ...    0.896659    0.998862    1.113278
min       0.000000    NaN    NaN  ...    1.000000    1.000000    1.000000
25%       2.000000    NaN    NaN  ...    4.000000    3.000000    2.000000
50%       2.000000    NaN    NaN  ...    4.000000    3.000000    3.000000
75%       3.000000    NaN    NaN  ...    5.000000    4.000000    4.000000
max       4.000000    NaN    NaN  ...    5.000000    5.000000    5.000000

              Dalc        Walc      health    absences          G1  \
count   395.000000  395.000000  395.000000  395.000000  395.000000
unique         NaN         NaN         NaN         NaN         NaN
top            NaN         NaN         NaN         NaN         NaN
freq           NaN         NaN         NaN         NaN         NaN
mean      1.481013    2.291139    3.554430    5.708861   10.908861
std       0.890741    1.287897    1.390303    8.003096    3.319195
min       1.000000    1.000000    1.000000    0.000000    3.000000
25%       1.000000    1.000000    3.000000    0.000000    8.000000
50%       1.000000    2.000000    4.000000    4.000000   11.000000
75%       2.000000    3.000000    5.000000    8.000000   13.000000
max       5.000000    5.000000    5.000000   75.000000   19.000000

                G2          G3
count   395.000000  395.000000
unique         NaN         NaN
top            NaN         NaN
freq           NaN         NaN
mean     10.713924   10.415190
std       3.761505    4.581443
min       0.000000    0.000000
25%       9.000000    8.000000
50%      11.000000   11.000000
75%      13.000000   14.000000
max      19.000000   20.000000

[11 rows x 33 columns]
<bound method DataFrame.count of     school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0    ...      4        3      4     1     1      3        6   5   6   6
1    ...      5        3      3     1     1      3        4   5   5   6
2    ...      4        3      2     2     3      3       10   7   8  10
3    ...      3        2      2     1     1      5        2  15  14  15
4    ...      4        3      2     1     2      5        4   6  10  10
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[395 rows x 33 columns]>
school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64
school         2
sex            2
age            8
address        2
famsize        2
Pstatus        2
Medu           5
Fedu           5
Mjob           5
Fjob           5
reason         4
guardian       3
traveltime     4
studytime      4
failures       4
schoolsup      2
famsup         2
paid           2
activities     2
nursery        2
higher         2
internet       2
romantic       2
famrel         5
freetime       5
goout          5
Dalc           5
Walc           5
health         5
absences      34
G1            17
G2            17
G3            18
dtype: int64
school  sex  age  address  famsize  Pstatus  Medu  Fedu  Mjob      Fjob      reason      guardian  traveltime  studytime  failures  schoolsup  famsup  paid  activities  nursery  higher  internet  romantic  famrel  freetime  goout  Dalc  Walc  health  absences  G1  G2  G3
MS      M    21   R        GT3      T        1     1     other     other     course      other     1           1          3         no         no      no    no          no       yes     no        no        5       5         3      3     3     3       3         10  8   7     1
GP      F    15   R        GT3      T        1     1     at_home   other     home        mother    2           4          1         yes        yes     yes   yes         yes      yes     yes       no        3       1         2      1     1     1       2         7   10  10    1
                                                         other     other     reputation  mother    1           2          2         yes        yes     no    no          no       yes     yes       yes       3       3         4      2     4     5       2         8   6   5     1
                                             2     2     at_home   other     reputation  mother    1           1          0         yes        yes     yes   yes         yes      yes     no        no        4       3         1      1     1     2       8         14  13  13    1
                                                   4     services  health    course      mother    1           3          0         yes        yes     yes   yes         yes      yes     yes       no        4       3         2      1     1     5       2         10  9   8     1
                                                                                                                                                                                                                                                                                  ..
                  U        GT3      T        1     2     at_home   services  course      mother    1           2          0         no         no      no    no          no       yes     yes       no        3       2         3      1     2     1       2         16  15  15    1
                                                                   other     course      mother    1           2          0         no         yes     yes   no          no       yes     yes       no        4       3         2      1     1     5       2         10  11  11    1
                                                   1     other     services  course      father    1           2          0         no         yes     yes   no          yes      yes     yes       no        4       4         2      1     2     5       0         8   11  11    1
                                                                   other     home        father    1           2          0         no         yes     no    yes         no       yes     yes       no        4       3         2      2     3     4       2         9   10  10    1
                                                         at_home   other     course      mother    3           1          0         no         yes     no    yes         no       yes     yes       yes       4       3         3      1     2     4       0         8   0   0     1
Name: count, Length: 395, dtype: int64

# **Module 4- Selecting Data**

In [ ]:
import pandas as pd

df = pd.read_csv("/content/Employee.csv")

print(df["Gender"]) # Selecting a Single Column
df[["Education", "City"]] # selecting multiple columns

#Selecting Rows using Index

print(df.iloc[0]) # first row
print(df.iloc[0:5]) # multiple rows
print(df.iloc[-5:]) # last five rows

## Selecting Rows and Columns using loc[]

#loc[] uses row labels (index names) and column names.
# syntax -> df.loc[row_label, column_name]
print(df.loc[0]) # first row
print(df.loc[0:5]) # multiple rows
print(df.loc[-5:]) # last five rows

#Selecting Rows and Columns using iloc[]

#iloc[] uses integer positions.
#syntax -> df.iloc[row_index, column_index]

print(df.iloc[0]) #first row
print(df.iloc[0:5]) #multiple rows
print(df.iloc[-5:]) #last five rows

# Boolean Indexing

#Boolean Indexing returns rows where the condition is True.

# Age greater than 30
df[df["Age"] > 30]

# Age less than 30
df[df["Age"] < 30]
# city is banglore
df[df["City"] == "Bangalore"]

# education is master
df[df["Education"] == "Masters"]

# Filtering Data

df[df["City"] == "Bangalore"] # single condition
df[(df["City"] == "Pune") & # multiple conditions(AND) (
   (df["Age"] > 30)]

df[(df["City"] == "Pune") | # multiple conditions(OR)
   (df["Age"] > 30)]

df[~(df["City"] == "New Delhi")] # NOT condition (changed from Department == Sales)

df[df["City"].isin(["Bangalore", "Pune"])] # using isin()

df[df["Age"].between(25, 35)] # using(between)

df[df["Education"].str.contains("Bachelor", case=False)] # using str.contains()
# using query
df.query("Age > 30")
df.query("City == 'Pune'")
df.query("Age > 30 and ExperienceInCurrentDomain > 3")

df.nlargest(5, "Age") # using nlargest()
df.nsmallest(5, "Age") # using nsmallest()

0         Male
1       Female
2       Female
3         Male
4         Male
         ...
4648    Female
4649      Male
4650      Male
4651      Male
4652      Male
Name: Gender, Length: 4653, dtype: object
Education                    Bachelors
JoiningYear                       2017
City                         Bangalore
PaymentTier                          3
Age                                 34
Gender                            Male
EverBenched                         No
ExperienceInCurrentDomain            0
LeaveOrNot                           0
Name: 0, dtype: object
   Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No
1  Bachelors         2013       Pune            1   28  Female          No
2  Bachelors         2014  New Delhi            3   38  Female          No
3    Masters         2016  Bangalore            3   27    Male          No
4    Masters         2017       Pune            3   24    Male         Yes

   ExperienceInCurrentDomain  LeaveOrNot
0                          0           0
1                          3           1
2                          2           0
3                          5           1
4                          2           1
      Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
4648  Bachelors         2013  Bangalore            3   26  Female          No
4649    Masters         2013       Pune            2   37    Male          No
4650    Masters         2018  New Delhi            3   27    Male          No
4651  Bachelors         2012  Bangalore            3   30    Male         Yes
4652  Bachelors         2015  Bangalore            3   33    Male         Yes

      ExperienceInCurrentDomain  LeaveOrNot
4648                          4           0
4649                          2           1
4650                          5           1
4651                          2           0
4652                          4           0
Education                    Bachelors
JoiningYear                       2017
City                         Bangalore
PaymentTier                          3
Age                                 34
Gender                            Male
EverBenched                         No
ExperienceInCurrentDomain            0
LeaveOrNot                           0
Name: 0, dtype: object
   Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No
1  Bachelors         2013       Pune            1   28  Female          No
2  Bachelors         2014  New Delhi            3   38  Female          No
3    Masters         2016  Bangalore            3   27    Male          No
4    Masters         2017       Pune            3   24    Male         Yes
5  Bachelors         2016  Bangalore            3   22    Male          No

   ExperienceInCurrentDomain  LeaveOrNot
0                          0           0
1                          3           1
2                          2           0
3                          5           1
4                          2           1
5                          0           0
      Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0     Bachelors         2017  Bangalore            3   34    Male          No
1     Bachelors         2013       Pune            1   28  Female          No
2     Bachelors         2014  New Delhi            3   38  Female          No
3       Masters         2016  Bangalore            3   27    Male          No
4       Masters         2017       Pune            3   24    Male         Yes
...         ...          ...        ...          ...  ...     ...         ...
4648  Bachelors         2013  Bangalore            3   26  Female          No
4649    Masters         2013       Pune            2   37    Male          No
4650    Masters         2018  New Delhi            3   27    Male          No
4651  Bachelors         2012  Bangalore            3   30    Male         Yes
4652  Bachelors         2015  Bangalore            3   33    Male         Yes

      ExperienceInCurrentDomain  LeaveOrNot
0                             0           0
1                             3           1
2                             2           0
3                             5           1
4                             2           1
...                         ...         ...
4648                          4           0
4649                          2           1
4650                          5           1
4651                          2           0
4652                          4           0

[4653 rows x 9 columns]
Education                    Bachelors
JoiningYear                       2017
City                         Bangalore
PaymentTier                          3
Age                                 34
Gender                            Male
EverBenched                         No
ExperienceInCurrentDomain            0
LeaveOrNot                           0
Name: 0, dtype: object
   Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No
1  Bachelors         2013       Pune            1   28  Female          No
2  Bachelors         2014  New Delhi            3   38  Female          No
3    Masters         2016  Bangalore            3   27    Male          No
4    Masters         2017       Pune            3   24    Male         Yes

   ExperienceInCurrentDomain  LeaveOrNot
0                          0           0
1                          3           1
2                          2           0
3                          5           1
4                          2           1
      Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
4648  Bachelors         2013  Bangalore            3   26  Female          No
4649    Masters         2013       Pune            2   37    Male          No
4650    Masters         2018  New Delhi            3   27    Male          No
4651  Bachelors         2012  Bangalore            3   30    Male         Yes
4652  Bachelors         2015  Bangalore            3   33    Male         Yes

      ExperienceInCurrentDomain  LeaveOrNot
4648                          4           0
4649                          2           1
4650                          5           1
4651                          2           0
4652                          4           0

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0
19,Bachelors,2016,New Delhi,2,22,Female,No,0,1
25,Bachelors,2013,Bangalore,3,22,Female,Yes,0,0
63,Bachelors,2014,Pune,1,22,Female,No,0,1
91,Bachelors,2015,New Delhi,3,22,Male,No,0,0

# **Module 5- Missing Values in Pandas**

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Aman", "Riya", "Karan", "Priya", np.nan],
    "Age": [22, np.nan, 25, 28, 24],
    "City": ["Delhi", "Mumbai", np.nan, "Lucknow", "Delhi"],
    "Salary": [50000, 60000, np.nan, 75000, 55000]
}

df = pd.DataFrame(data)

print("Original DataFrame")
print(df)
print(df.isnull()) #. used to identify missing value
print(df.isnull().sum()) # count missing value
print(df.notnull()) #. used to identify missing value
# fill with a constant
filled = df.fillna("Unknown")
print(filled)
# fill numeric coulmns
df["Age"] = df["Age"].fillna(df["Age"].mean())

print(df)
# fill multiple columns
df.fillna({
    "Name": "Not Available",
    "City": "Unknown",
    "Salary": 0
}, inplace=True)

print(df)

df.dropna() # removes missing values
# df.replace(old_value, new_value) # used to replace speific values (not limited to missing values)

Original DataFrame
    Name   Age     City   Salary
0   Aman  22.0    Delhi  50000.0
1   Riya   NaN   Mumbai  60000.0
2  Karan  25.0      NaN      NaN
3  Priya  28.0  Lucknow  75000.0
4    NaN  24.0    Delhi  55000.0
    Name    Age   City  Salary
0  False  False  False   False
1  False   True  False   False
2  False  False   True    True
3  False  False  False   False
4   True  False  False   False
Name      1
Age       1
City      1
Salary    1
dtype: int64
    Name    Age   City  Salary
0   True   True   True    True
1   True  False   True    True
2   True   True  False   False
3   True   True   True    True
4  False   True   True    True
      Name      Age     City   Salary
0     Aman     22.0    Delhi  50000.0
1     Riya  Unknown   Mumbai  60000.0
2    Karan     25.0  Unknown  Unknown
3    Priya     28.0  Lucknow  75000.0
4  Unknown     24.0    Delhi  55000.0
    Name    Age     City   Salary
0   Aman  22.00    Delhi  50000.0
1   Riya  24.75   Mumbai  60000.0
2  Karan  25.00      NaN      NaN
3  Priya  28.00  Lucknow  75000.0
4    NaN  24.00    Delhi  55000.0
            Name    Age     City   Salary
0           Aman  22.00    Delhi  50000.0
1           Riya  24.75   Mumbai  60000.0
2          Karan  25.00  Unknown      0.0
3          Priya  28.00  Lucknow  75000.0
4  Not Available  24.00    Delhi  55000.0

            Name    Age     City   Salary
0           Aman  22.00    Delhi  50000.0
1           Riya  24.75   Mumbai  60000.0
2          Karan  25.00  Unknown      0.0
3          Priya  28.00  Lucknow  75000.0
4  Not Available  24.00    Delhi  55000.0

# **Module 6- Sorting**

***Create employee data set.***

In [ ]:
import pandas as pd

data = {
    "Emp_id":[105, 101, 104, 102, 103],
    "Name":["Aman", "Riya", "Rahul", "Priya", "Karan"],
    "Department":["HR", "IT", "Finance", "IT", "HR"],
    "Salary": [45000, 60000, 55000, 65000, 50000],
    "Age":[28,24,35,30,27]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df.sort_values(by="Column_Name") #sort data based on one or more column values
print(df.sort_values(by="Age", ascending=True)) #sort in ascending order(default)
print(df.sort_values(by="Salary", ascending=False)) #sort in descending order
print(df.sort_values(by=["Department", "Salary"])) #sort by multiple columns
print(df.sort_index()) #sort by index

Original DataFrame:
   Emp_id   Name Department  Salary  Age
0     105   Aman         HR   45000   28
1     101   Riya         IT   60000   24
2     104  Rahul    Finance   55000   35
3     102  Priya         IT   65000   30
4     103  Karan         HR   50000   27

KeyError: 'Column_Name'

# **Module 7- Data Cleaning**

**Topics**

***duplicated()***

***drop_duplicates()***

***rename()***

***astype()***

***replace()***

# **1. duplicated()**

***find duplicate values***

In [ ]:
import pandas as pd

# Sample Data
data = {
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Amit", "Rahul", "Rohan", "Rahul", "Neha"],
    "City": ["Delhi", "Mumbai", "Pune", "Pune", "Lucknow"]
}

df = pd.DataFrame(data)

print(df)

print("\nDuplicate Rows:")
print(df.duplicated())

    ID   Name     City
0  101   Amit    Delhi
1  102  Rahul   Mumbai
2  103  Rohan     Pune
3  104  Rahul     Pune
4  105   Neha  Lucknow

Duplicate Rows:
0    False
1    False
2    False
3    False
4    False
dtype: bool

# **2. drop_duplicates()**

***Remove duplicate rows.***

In [ ]:
import pandas as pd

# Sample Data
data = {
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Amit", "Rahul", "Rohan", "Rahul", "Neha"],
    "City": ["Delhi", "Mumbai", "Pune", "Pune", "Lucknow"]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Remove duplicate rows
df = df.drop_duplicates()

print("\nDataFrame after removing duplicates:")
print(df)

Original DataFrame:
    ID   Name     City
0  101   Amit    Delhi
1  102  Rahul   Mumbai
2  103  Rohan     Pune
3  104  Rahul     Pune
4  105   Neha  Lucknow

DataFrame after removing duplicates:
    ID   Name     City
0  101   Amit    Delhi
1  102  Rahul   Mumbai
2  103  Rohan     Pune
3  104  Rahul     Pune
4  105   Neha  Lucknow

# **3. rename()**

***Rename columns name.***

In [ ]:
import pandas as pd

data = {
    "Emp_id" : [101, 102, 103],
    "Name" : ["Amit", "Rahul", "Rohan"],
    "Department" : ["HR", "IT", "Finance"],
    "Salary" : [45000, 60000, 55000]
}

df = pd.DataFrame(data)

print("Original Columns:")
print(df)

df = df.rename(columns={
    "Emp_ID" : "ID",
    "Emp_Name" : "Name",

})

print("\nAfter Renaming:")
print(df)

Original Columns:
   Emp_id   Name Department  Salary
0     101   Amit         HR   45000
1     102  Rahul         IT   60000
2     103  Rohan    Finance   55000

After Renaming:
   Emp_id   Name Department  Salary
0     101   Amit         HR   45000
1     102  Rahul         IT   60000
2     103  Rohan    Finance   55000

# **4. astype()**

***Change the data type of a column.***

In [ ]:
import pandas as pd

data = {
    "ID" : ["101", "102", "103"],
    "Salary" : ["45000", "60000", "55000"]
}

df = pd.DataFrame(data)

print("Before Conversion:")
print(df.dtypes)

df["ID"] = df["ID"].astype(int)
df["Salary"] = df["Salary"].astype(float)

print("\nAfter Conversion:")
print(df.dtypes)

print(df)

Before Conversion:
ID        object
Salary    object
dtype: object

After Conversion:
ID          int64
Salary    float64
dtype: object
    ID   Salary
0  101  45000.0
1  102  60000.0
2  103  55000.0

# **5. Replace()**

***Replace values in a DataFrame.***

In [ ]:
import pandas as pd

data = {
    "Name":["Amit", "Rahul", "Rohan"],
    "City":["Delhi", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df["City"] = df["City"].replace("Delhi", "New Delhi")

print("\nDataFrame after replacing:")
print(df)

Original DataFrame:
    Name    City
0   Amit   Delhi
1  Rahul  Mumbai
2  Rohan    Pune

DataFrame after replacing:
    Name       City
0   Amit  New Delhi
1  Rahul     Mumbai
2  Rohan       Pune

# **Module 8 - String Functions**

**Topics**.str

***lower()***

***upper()***

***contains()***

***split()***

***replace()***

***strip()***

In [ ]:
import pandas as pd

# Sample Dataset
df = pd.DataFrame({
    "Name": ["Amit", "Priya", "Rahul", "Neha", "David"]
})

print(df)

# .str.lower() -> converts all text to lowercase
df["Lower"] = df["Name"].str.lower()

print(df)

# .str.upper() -> Converts all text to uppercase.
df["Upper"] = df["Name"].str.upper()

print(df)

# .str.contains() -> Checks whether a string contains a specific word or character.
df["Contains_a"] = df["Name"].str.contains("a", case=False)

print(df)

# .str.split() -> Splits a string into multiple parts.
df["Split"] = df["Name"].str.split()

print(df)

# .str.replace() -> Replaces a word or character with another.
df["Replaced"] = df["Name"].str.replace("a", "A")

print(df)

# .str.strip() -> Removes leading and trailing spaces.
df["Stripped"] = df["Name"].str.strip()

print(df)

    Name
0   Amit
1  Priya
2  Rahul
3   Neha
4  David
    Name  Lower
0   Amit   amit
1  Priya  priya
2  Rahul  rahul
3   Neha   neha
4  David  david
    Name  Lower  Upper
0   Amit   amit   AMIT
1  Priya  priya  PRIYA
2  Rahul  rahul  RAHUL
3   Neha   neha   NEHA
4  David  david  DAVID
    Name  Lower  Upper  Contains_a
0   Amit   amit   AMIT        True
1  Priya  priya  PRIYA        True
2  Rahul  rahul  RAHUL        True
3   Neha   neha   NEHA        True
4  David  david  DAVID        True
    Name  Lower  Upper  Contains_a    Split
0   Amit   amit   AMIT        True   [Amit]
1  Priya  priya  PRIYA        True  [Priya]
2  Rahul  rahul  RAHUL        True  [Rahul]
3   Neha   neha   NEHA        True   [Neha]
4  David  david  DAVID        True  [David]
    Name  Lower  Upper  Contains_a    Split Replaced
0   Amit   amit   AMIT        True   [Amit]     Amit
1  Priya  priya  PRIYA        True  [Priya]    PriyA
2  Rahul  rahul  RAHUL        True  [Rahul]    RAhul
3   Neha   neha   NEHA        True   [Neha]     NehA
4  David  david  DAVID        True  [David]    DAvid
    Name  Lower  Upper  Contains_a    Split Replaced Stripped
0   Amit   amit   AMIT        True   [Amit]     Amit     Amit
1  Priya  priya  PRIYA        True  [Priya]    PriyA    Priya
2  Rahul  rahul  RAHUL        True  [Rahul]    RAhul    Rahul
3   Neha   neha   NEHA        True   [Neha]     NehA     Neha
4  David  david  DAVID        True  [David]    DAvid    David

# **Module 9-GroupBy**

**Topics**

***groupby()***

***mean()***

***sum()***

***count()***

***agg()***

In [ ]:
import pandas as pd

data = {
    "Employee": ["Aman", "Riya", "Rahul", "Priya", "Karan", "Neha"],
    "Department": ["HR", "IT", "IT", "HR", "Sales", "Sales"],
    "Salary": [40000, 60000, 55000, 45000, 50000, 52000]
}

df = pd.DataFrame(data)

print(df.groupby("Department")) # group by object
print(df.groupby("Department")["Salary"].mean()) # mean of 'Salary' for each group
print(df.groupby("Department")["Salary"].sum()) # sum of 'Salary' for each group
print(df.groupby("Department").count()) # count of each group
print(df.groupby("Department").agg({"Salary": ["mean", "sum"]})) # aggregate

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7ab98c98bf80>
Department
HR       42500.0
IT       57500.0
Sales    51000.0
Name: Salary, dtype: float64
Department
HR        85000
IT       115000
Sales    102000
Name: Salary, dtype: int64
            Employee  Salary
Department
HR                 2       2
IT                 2       2
Sales              2       2
             Salary
               mean     sum
Department
HR          42500.0   85000
IT          57500.0  115000
Sales       51000.0  102000